// BannerConstants.js
export const BANNER_LIST_REQUEST = 'BANNER_LIST_REQUEST';
export const BANNER_LIST_SUCCESS = 'BANNER_LIST_SUCCESS';
export const BANNER_LIST_FAIL = 'BANNER_LIST_FAIL';

export const BANNER_DELETE_REQUEST = 'BANNER_DELETE_REQUEST';
export const BANNER_DELETE_SUCCESS = 'BANNER_DELETE_SUCCESS';
export const BANNER_DELETE_FAIL = 'BANNER_DELETE_FAIL';

export const DELETE_BANNER_RESET = 'DELETE_BANNER_RESET';
